import { agentPath, type EveProject, type Subagent } from "@evelab/eve-project";
import { scanRequiredEnv } from "@/lib/env-scan";

/**
 * The README and .env.example evelab keeps beside every project. Both are
 * derived from the source, so they stay true as the architecture changes. Each
 * starts with a marker line; delete it and evelab never touches the file again.
 */

export const README_PATH = "README.md";
export const ENV_EXAMPLE_PATH = ".env.example";
export const README_MARKER =
  "<!-- Generated by evelab from this project's source. Delete this line to keep your own edits. -->";
export const ENV_MARKER = "# Generated by evelab from this project's source. Delete this line to keep your own edits.";

export interface EnvEntry {
  name: string;
  purpose: string;
  files: string[];
}

export interface EnvGroup {
  title: string;
  entries: EnvEntry[];
}

type Owner = Pick<EveProject, "tools" | "skills" | "connections" | "subagents">;

function modelEntries(project: EveProject): EnvEntry[] {
  const expression = project.agent.model?.expression ?? "";
  const files = [agentPath(project.root, "agent.ts")];
  if (/\banthropic\(/.test(expression)) {
    return [{ name: "ANTHROPIC_API_KEY", purpose: "Anthropic API key for the model in agent.ts.", files }];
  }
  if (/\bopenai\(/.test(expression)) {
    return [{ name: "OPENAI_API_KEY", purpose: "OpenAI API key for the model in agent.ts.", files }];
  }
  // A ChatGPT subscription signs in on the first eve dev instead of reading a key.
  if (/\bchatgpt\(/.test(expression)) return [];
  return [
    {
      name: "AI_GATEWAY_API_KEY",
      purpose: "AI Gateway key for eve dev. Deployed on Vercel, the project's OIDC token is used instead, so it is optional there.",
      files,
    },
  ];
}

/** Every variable the agent reads, grouped by the part of the project that reads it. */
export function envGroups(project: EveProject): EnvGroup[] {
  const groups = new Map<string, EnvEntry[]>([
    ["Model", modelEntries(project)],
    ["Channels", []],
    ["Connections", []],
    ["Tools", []],
    ["Other", []],
  ]);
  const taken = new Set(groups.get("Model")!.map((entry) => entry.name));

  const usesConnect = project.files.some((file) => /\.(m?[jt]sx?)$/.test(file.path) && file.content.includes("@vercel/connect"));
  if (usesConnect) {
    groups.get("Connections")!.push({
      name: "VERCEL_OIDC_TOKEN",
      purpose: "Lets Vercel Connect resolve connector credentials during eve dev. Fill it with vercel env pull; deployments get it automatically.",
      files: [],
    });
    taken.add("VERCEL_OIDC_TOKEN");
  }

  for (const entry of scanRequiredEnv(project.files)) {
    if (taken.has(entry.name)) continue;
    const first = entry.files[0] ?? "";
    const group = /(^|\/)channels\//.test(first)
      ? "Channels"
      : /(^|\/)connections\//.test(first)
        ? "Connections"
        : /(^|\/)tools\//.test(first)
          ? "Tools"
          : "Other";
    const purpose =
      group === "Channels"
        ? "Read by a channel adapter."
        : group === "Connections"
          ? "Credential for a connection."
          : group === "Tools"
            ? "Read by a tool."
            : "Read by the agent's code.";
    groups.get(group)!.push({ name: entry.name, purpose, files: entry.files });
  }

  return [...groups].filter(([, entries]) => entries.length > 0).map(([title, entries]) => ({ title, entries }));
}

export function renderEnvExample(project: EveProject): string {
  const lines = [
    ENV_MARKER,
    "# Copy this file to .env.local for eve dev, and set the same names on the Vercel project before deploying.",
    "# Never commit real values: .env.local stays out of git.",
    "",
  ];
  const groups = envGroups(project);
  if (groups.length === 0) lines.push("# This agent reads no environment variables yet.", "");
  for (const group of groups) {
    lines.push(`# ${group.title}`);
    for (const entry of group.entries) {
      const where = entry.files.length > 0 ? ` Used in ${entry.files.join(", ")}.` : "";
      lines.push(`# ${entry.purpose}${where}`, `${entry.name}=`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

const CHANNEL_LABELS: Record<string, string> = {
  eve: "HTTP session API",
  slack: "Slack",
  discord: "Discord",
  teams: "Microsoft Teams",
  telegram: "Telegram",
  twilio: "Twilio",
  github: "GitHub",
  linear: "Linear",
  linq: "Linq",
  photon: "Photon",
  mcp: "MCP clients",
  "chat-sdk": "Chat SDK adapter",
  custom: "Custom channel",
  disabled: "Disabled route",
};

function script(project: EveProject, name: string, fallback: string): string {
  try {
    const pkg = JSON.parse(project.files.find((file) => file.path === "package.json")?.content ?? "{}") as {
      scripts?: Record<string, string>;
    };
    return pkg.scripts?.[name] ? `npm run ${name}` : fallback;
  } catch {
    return fallback;
  }
}

function names(owner: Owner): string[] {
  return [...owner.tools, ...owner.skills, ...owner.connections].map((entry) => `\`${entry.id}\``);
}

/** Every local subagent, nested ones included. */
function walk(subagents: Subagent[]): Owner[] {
  return subagents.flatMap((subagent) => (subagent.kind === "local" ? [subagent as Owner, ...walk(subagent.subagents)] : []));
}

function subagentLines(subagents: Subagent[], depth: number): string[] {
  return subagents.flatMap((subagent) => {
    const indent = "  ".repeat(depth);
    if (subagent.kind !== "local") return [`${indent}- **${subagent.id}**: a remote agent.`];
    const model = subagent.model?.id || (subagent.model?.expression ? "model set in code" : "default model");
    const resources = names(subagent);
    const uses = resources.length > 0 ? ` Uses ${resources.join(", ")}.` : "";
    return [
      `${indent}- **${subagent.id}** (\`${model}\`): ${subagent.description || "No description yet."}${uses}`,
      ...subagentLines(subagent.subagents, depth + 1),
    ];
  });
}

function list(title: string, entries: { id: string; description?: string }[]): string[] {
  if (entries.length === 0) return [];
  return [`### ${title}`, "", ...entries.map((entry) => `- \`${entry.id}\`${entry.description ? `: ${entry.description}` : ""}`), ""];
}

export function renderReadme(project: EveProject): string {
  const { agent } = project;
  const base = project.root ? `${project.root}/` : "";
  const model = agent.model?.id || agent.model?.expression || "eve's default model";
  const dev = script(project, "dev", "npx eve dev");
  const deploy = script(project, "deploy", "npx eve deploy");
  const everyone = [project as Owner, ...walk(project.subagents)];
  const total = (key: "tools" | "skills" | "connections") => everyone.reduce((sum, owner) => sum + owner[key].length, 0);
  const has = (directory: string) => project.files.some((file) => file.path.startsWith(`${base}${directory}/`));

  const tree: [string, string][] = [
    ["agent.ts", "model and options"],
    ["instructions.md", "the system prompt"],
  ];
  if (has("channels")) tree.push(["channels/", "routes at /eve/v1/<name>"]);
  if (has("tools")) tree.push(["tools/", "TypeScript tools"]);
  if (has("skills")) tree.push(["skills/", "skills loaded on demand"]);
  if (has("connections")) tree.push(["connections/", "MCP servers and OpenAPI services"]);
  if (has("subagents")) tree.push(["subagents/", "specialists, one folder each"]);
  if (has("schedules")) tree.push(["schedules/", "cron prompts"]);
  if (has("lib")) tree.push(["lib/", "definitions shared by several agents"]);

  const lines: string[] = [README_MARKER, "", `# ${agent.name}`, ""];
  if (agent.description) lines.push(agent.description, "");
  lines.push(
    `An [eve](https://eve.dev) agent. eve compiles the files under \`${base || "./"}\` into a durable backend agent. This project was built with evelab and runs exactly the same without it.`,
    "",
    "## What eve gives you",
    "",
    "- **Durable sessions.** Every conversation is a workflow that survives restarts, deploys and long tool calls.",
    "- **Channels.** Each file in `channels/` is a route at `/eve/v1/<name>`: the HTTP session API, Slack, GitHub, Chat SDK adapters and more.",
    "- **Tools, skills and connections.** TypeScript tools, markdown skills loaded only when a task needs them, and remote MCP or OpenAPI services.",
    "- **Subagents.** Specialists with their own model, instructions and resources. A subagent inherits nothing from its parent.",
    "- **Schedules.** Markdown prompts with a cron that start sessions on their own.",
    "- **A sandbox.** A bash workspace the agent can use, on Vercel Sandbox when deployed.",
    "",
    "## Architecture",
    "",
    "| | |",
    "| --- | --- |",
    `| Model | \`${model}\` |`,
    `| Channels | ${project.channels.length} |`,
    `| Subagents | ${walk(project.subagents).length} |`,
    `| Tools | ${total("tools")} |`,
    `| Skills | ${total("skills")} |`,
    `| Connections | ${total("connections")} |`,
    `| Schedules | ${project.schedules.length} |`,
    "",
  );

  lines.push("### Channels", "");
  if (project.channels.length === 0) {
    lines.push("eve serves its default HTTP session API at `/eve/v1/eve`.", "");
  } else {
    for (const channel of project.channels) {
      lines.push(`- \`${channel.id}\` at \`/eve/v1/${channel.id}\` (${CHANNEL_LABELS[channel.kind] ?? "channel"})`);
    }
    lines.push("");
  }

  if (project.subagents.length > 0) lines.push("### Subagents", "", ...subagentLines(project.subagents, 0), "");
  lines.push(
    ...list("Tools", project.tools.filter((tool) => !tool.shared)),
    ...list("Skills", project.skills.filter((skill) => !skill.shared)),
    ...list("Connections", project.connections.filter((connection) => !connection.shared)),
  );

  const shared = [...project.library.tools, ...project.library.skills, ...project.library.connections];
  if (shared.length > 0) {
    lines.push(
      "### Shared resources",
      "",
      "Defined once in `lib/` and re-exported by each agent that uses it, so a change reaches every agent.",
      "",
      ...shared.map((entry) => `- \`${entry.id}\`${entry.description ? `: ${entry.description}` : ""}`),
      "",
    );
  }

  if (project.schedules.length > 0) {
    lines.push("### Schedules", "", ...project.schedules.map((schedule) => `- \`${schedule.id}\`: \`${schedule.cron}\``), "");
  }

  lines.push(
    "## Project layout",
    "",
    "```text",
    `${base || "./"}`,
    ...tree.map(([name, note], index) => `${index === tree.length - 1 ? "└──" : "├──"} ${name.padEnd(17)} ${note}`),
    "```",
    "",
    "## Run it locally",
    "",
    "1. Use Node 24, then install dependencies:",
    "",
    "   ```bash",
    "   npm install",
    "   ```",
    "",
    "2. Create a local environment file and fill in the values listed below:",
    "",
    "   ```bash",
    "   cp .env.example .env.local",
    "   ```",
    "",
    "3. Start the agent:",
    "",
    "   ```bash",
    `   ${dev}`,
    "   ```",
    "",
    "   eve starts its dev server and terminal UI. Messages run through the same channels, tools and subagents as in production.",
    "",
    "## Deploy",
    "",
    "```bash",
    deploy,
    "```",
    "",
    "`eve deploy` links or creates a Vercel project. There, sessions run on Workflow, the agent's shell on Sandbox, schedules on Cron, and model calls through AI Gateway with the project's OIDC token. Set the environment variables below on the Vercel project first.",
    "",
    "## Environment variables",
    "",
  );

  const groups = envGroups(project);
  if (groups.length === 0) {
    lines.push("This agent reads no environment variables yet.", "");
  } else {
    lines.push("| Variable | Group | What it is for |", "| --- | --- | --- |");
    for (const group of groups) {
      for (const entry of group.entries) lines.push(`| \`${entry.name}\` | ${group.title} | ${entry.purpose} |`);
    }
    lines.push("", "`.env.example` lists the same variables with the files that read them.", "");
  }

  lines.push(
    "## Learn more",
    "",
    "- [eve documentation](https://eve.dev/docs)",
    "- [Agent configuration](https://eve.dev/docs/agent-config)",
    "- [Vercel AI Gateway](https://vercel.com/docs/ai-gateway)",
    "- [Vercel Connect](https://vercel.com/docs/connect)",
  );
  return `${lines.join("\n")}\n`;
}
